@echo off
cls
echo Stop containers...
docker stop api web db seq
echo Remove containers...
docker rm api web db seq
echo Clearing containers...
docker container prune -f

echo ...
echo Remove networks...
docker network rm web-store
echo Clearing networks...
docker network prune -f

echo ...
echo Clearing system...
docker system prune -f
docker system df

echo ...
echo Remove binaries...
rmdir /s /q publish 

rem docker exec api rm -r /app
rem docker exec web rm -r /app
echo ...
echo Clearing complete

pause
echo ...
echo ----------------------------------------
echo Compiling...
dotnet publish -c release -r linux-x64 -o publish/api Services\WebStore.ServiceHosting 
dotnet publish -c release -r linux-x64 -o publish/web UI\WebStore 

echo ...
echo Create network "web-store"
docker network create web-store

echo ...
echo Run logs and db containers...
echo    -- seq
docker run --name seq -itd --net web-store -p 5003:80 infarh/seq
echo    -- db
docker run --name db -itd --net web-store infarh/mssql

echo ...
echo Run primary containers...
echo    -- api
docker run --name api -itd --net web-store infarh/dotnet5 bash
echo    -- web
docker run --name web -itd --net web-store -p 5002:80 infarh/dotnet5 bash
rem docker container create --name api -it --net web-store infarh/dotnet5
rem docker container create --name web -it --net web-store infarh/dotnet5

echo ...
echo Copining binaries to containers...
echo    -- api
docker cp publish\api api:/app 
echo    -- web
docker cp publish\web web:/app

echo ...
echo Starting main containers
echo    -- api
docker exec -d -w /app api bash -c /app/WebStore.API
echo    -- web
docker exec -d -w /app web bash -c /app/WebStore

echo ...
echo Completed!